### ISSUE TITLE
Implement a search bar for the user to search the text in posts

### ISSUE THREAD

**Issue by lpcrosby** [CMU-313/spring24-nodebb-over-20#2]
Estimated effort: several hours?
Dependencies: none
Acceptance criteria: search bar exists, it takes in user input correctly, and passes that input to a search function.

**Comment by Yunirang** [comment]
Reminders for myself:

Search bar location: /Users/chaeilyun/Desktop/17313-3/spring24-nodebb-over-20/themes/nodebb-theme-persona/templates/category.tpl

**Comment by Yunirang** [comment]
Made changes to the file 
public/src/admin/manage/categories.js

for function that handles category search
